#!/bin/bash
###  InterGenOS_build_002 linpack_inst_ext - A supplemental linpack installation script
###  Written by Christopher 'InterGen' Cork <chris@intergenstudios.com>
###  3/14/2015
#
# linpack_inst_ext scripts will be uniquely created for each package during package
# compilation, performing necessary installation steps outside of directory structure
# creation and symlink placement.  The scripts will be called as one of the final  
# installation commands for the package, and will call post installation scripts at
# their conclusion

CUR="$(pwd)"
BNM="$(basename "$CUR")"
ILL="$CUR"/"$BNM.inst_log"

echo " " >> $ILL
echo " " >> $ILL
echo "===========================================================" >> $ILL
echo " ##  Start of '$BNM' linpack_inst_ext logging  ## " >> $ILL
echo "===========================================================" >> $ILL

ext_inst () {

echo No supplemental installation for this package # Edit as needed
# supplemental installation commands are done in function to provide logging

}

ext_inst 2>&1 | tee -a $ILL

echo " " >> $ILL
echo " " >> $ILL
echo "===========================================================" >> $ILL
echo " ##  End of '$BNM' linpack_inst_ext logging  ## " >> $ILL
echo "===========================================================" >> $ILL


exec ./linpack_post_inst
