#!/bin/bash
###  InterGenOS_build_002 linpack_post_inst - linpack post installation script
###  Written by Christopher 'InterGen' Cork <chris@intergenstudios.com>
###  3/14/2015
#
# linpack_post_inst scripts are responsible for moving tar packages 
# to /var/cache/linpack/{core,base,extended}, closing out installation log
# files, and moving them to /var/log/linpack/inst
#

CUR="$(pwd)"
BNM="$(basename "$CUR")"
ILL="$CUR"/"$BNM.inst_log"

echo " " >> $ILL
echo " " >> $ILL
echo "===========================================================" >> $ILL
echo " ##  END of '$BNM' Installation Log  ## " >> $ILL
echo "===========================================================" >> $ILL

mv ../"$BNM"_InterGen.tar.gz /var/cache/linpack/core

mkdir -pv /var/log/linpack/inst

mv $ILL /var/log/linpack/inst
